spring:
  config:
    import:
      - classpath:application-secret.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

server:
  servlet:
    session:
      cookie:
        same-site: strict
        secure: true
        http-only: true
  forward-headers-strategy: native