spring:

  config:
    import:
      - classpath:application-secret.properties

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;mode=mysql;DB_CLOSE_ON_EXIT=FALSE

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework: debug
