name: Continuous Deploy to Development Server

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Down and Up Containers
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SERVER_USERNAME }}
        key: ${{ secrets.DEV_SERVER_KEY }}
        script: |
          sudo docker compose pull
          sudo docker compose down --rmi local
          sudo docker compose up -d